/* The following code was generated by JFlex 1.4.3 on 9/04/17 22:22 */

package analizadorlex;

import java.io.File;

/**
 *
 * @author Carlos
 */
public class Main {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        String path = "C:/Users/Alondra/Documents/NetBeansProjects/Analizadorlex/src/analizadorlex/Lexer.flex";
        generarLexer(path);

    }
    public static void generarLexer(String path){
        File file=new File(path);
        JFlex.Main.generate(file);
    }
}